#!/bin/bash

# publish talks to <gh-pages>

set -e
shopt -s extglob

WORK_DIR=$(pwd)
GH_PAGES_DIR=$(mktemp -d)

echo "Publishing talks to <gh-pages>"

git clone --depth=1 "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/nikku/talks.git" $GH_PAGES_DIR

cd "$GH_PAGES_DIR"
git checkout --orphan gh-pages
git reset --hard

cp -r ${WORK_DIR}/talks/* .


if [[ "x$SKIP_COMMIT" = "x" ]]; then

  git config --local user.email "$GIT_USER_EMAIL"
  git config --local user.name "$GIT_USER_NAME"
  git config push.default simple

  # add all resources
  git add -A
  git commit -m "chore: update talks"
  git push -qf -u origin gh-pages &2>/dev/null
else
  echo "Skipping commit (SKIP_COMMIT=$SKIP_COMMIT)"
fi

cd "$WORK_DIR"