#!/bin/bash

# build talks with pfwr to <gh-pages>

set -e

echo "installing pfwr"
npm i -g pfwr

for d in ./*/
do
  if [ -f "$d/index.md" ]; then
    echo "building $d"

    npx pfwr "${d}index.md"
  fi
done